name: ml-time-series
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.7.2
  - seaborn=0.13.1
  - jupyter=1.0.0
  - jupyterlab=4.0.4
  - plotly=6.1.2
  - pyarrow=20.0.0
  - pip:  
      - ydata-profiling==4.16.1
    